// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoZKRwzmzcPCTqiZzdk7MC7NL34CguySY',
    appId: '1:198182031353:web:c04308c6d23ca805abb728',
    messagingSenderId: '198182031353',
    projectId: 'stu-budget',
    authDomain: 'stu-budget.firebaseapp.com',
    storageBucket: 'stu-budget.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb4QG6mYtSr3oDMgrbzNelKFNXP47WUyw',
    appId: '1:198182031353:android:fc3401b0638a45d3abb728',
    messagingSenderId: '198182031353',
    projectId: 'stu-budget',
    storageBucket: 'stu-budget.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClBbIrqMl0f7GMJtjZvUdfoTsrIqCl7o0',
    appId: '1:198182031353:ios:75409321fc0b61eeabb728',
    messagingSenderId: '198182031353',
    projectId: 'stu-budget',
    storageBucket: 'stu-budget.appspot.com',
    iosBundleId: 'com.example.stubudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClBbIrqMl0f7GMJtjZvUdfoTsrIqCl7o0',
    appId: '1:198182031353:ios:75409321fc0b61eeabb728',
    messagingSenderId: '198182031353',
    projectId: 'stu-budget',
    storageBucket: 'stu-budget.appspot.com',
    iosBundleId: 'com.example.stubudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoZKRwzmzcPCTqiZzdk7MC7NL34CguySY',
    appId: '1:198182031353:web:2d3e442a095d4033abb728',
    messagingSenderId: '198182031353',
    projectId: 'stu-budget',
    authDomain: 'stu-budget.firebaseapp.com',
    storageBucket: 'stu-budget.appspot.com',
  );
}
